Repository dnum-mi/basegun, pull requests merged in 2022-03, with the labels that each got.

#26 Feature/vuecli to vite
  Makefile
  backend/src/main.py
  docker-compose-dev.yml
  frontend/Dockerfile
  frontend/README.md
  frontend/babel.config.js
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Upload.vue
  frontend/src/main.js
  frontend/src/router/index.js
  frontend/vite.config.js
Labels: feature

#27 Feature/ci
  .github/release-drafter.yml
  .github/workflows/publish-image-github.yml
  .gitignore
  Makefile
  README.md
Labels: feature

#29 Feature/accueil
  frontend/src/App.vue
  frontend/src/components/Upload.vue
  frontend/src/views/Home.vue
Labels: feature

#30 Feature/update model efficientnetb7 20220301
  .gitignore
  Makefile
  README.md
  backend/Dockerfile
  backend/README.md
  backend/requirements.txt
  backend/src/main.py
  backend/src/model.py
  backend/src/yolov3.cfg
  docker-compose-dev.yml
  frontend/src/components/Upload.vue
Labels: feature

#31 Feature/resultats
  frontend/src/components/Upload.vue
Labels: feature

#33 Download model in container
  .gitignore
  Makefile
  backend/Dockerfile
  backend/README.md
  backend/src/main.py
  docker-compose-dev.yml
Labels: bug

#35 Feature/backend tests
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .gitignore
  backend/Dockerfile
  backend/README.md
  backend/src/main.py
  backend/src/model.py
  backend/tests/__init__.py
  backend/tests/revolver.jpg
  backend/tests/test_api.py
  backend/tests/test_model.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  frontend/README.md
  frontend/src/components/Upload.vue
Labels: feature

#40 Enhancement/components
  .gitignore
  frontend/src/components/HeaderMain.vue
  frontend/src/components/HelloWorld.vue
  frontend/src/components/ResultsComponent.vue
  frontend/src/components/Upload.vue
  frontend/src/components/UploadComponent.vue
  frontend/src/store.js
  frontend/src/views/Home.vue
Labels: enhancement

#43 Feature/vite pwa
  apple-touch-icon.png
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/apple-touch-icon.png
  frontend/public/img/icons/apple-touch-icon-120x120.png
  frontend/public/img/icons/apple-touch-icon-152x152.png
  frontend/public/img/icons/apple-touch-icon-180x180.png
  frontend/public/img/icons/apple-touch-icon-60x60.png
  frontend/public/img/icons/apple-touch-icon-76x76.png
  frontend/public/img/icons/apple-touch-icon.png
  frontend/public/img/icons/basegun-android-chrome-192x192.png
  frontend/public/img/icons/basegun-android-chrome-512x512.png
  frontend/public/img/icons/basegun-android-chrome-maskable-192x192.png
  frontend/public/img/icons/basegun-android-chrome-maskable-512x512.png
  frontend/public/img/icons/favicon-16x16.png
  frontend/public/img/icons/favicon-32x32.png
  frontend/public/img/icons/favicon.ico
  frontend/public/img/icons/msapplication-icon-144x144.png
  frontend/public/img/icons/mstile-150x150.png
  frontend/public/img/icons/safari-pinned-tab.svg
  frontend/public/manifest.json
  frontend/public/pwa-192x192.png
  frontend/public/pwa-512x512.png
  frontend/public/robots.txt
  frontend/src/main.js
  frontend/src/registerServiceWorker.js
  frontend/vite.config.js
  frontend/vue.config.js
Labels: feature

#45 New model EfficientNetB7 0.4% better than previous
  backend/Dockerfile
  backend/README.md
  backend/tests/test_api.py
  backend/tests/test_model.py
Labels: enhancement
