Repository dnum-mi/basegun, pull requests merged in 2022-05, with the labels that each got.

#53 Feature/logging
  .github/workflows/deploy.yml
  .github/workflows/develop.yml
  .github/workflows/release.yml
  .gitignore
  backend/requirements.txt
  backend/src/main.py
  backend/tests/test_api.py
  cd/README.md
  docker-compose-dev.yml
  docker-compose-prod.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ResultsComponent.vue
  frontend/src/components/UploadButton.vue
  frontend/src/store.js
  infra/README.md
  infra/filebeat.elastic.yml
  infra/img/openstack.png
  infra/scripts/deploy.sh
  infra/scripts/docker-push.sh
  infra/scripts/init.yaml
  infra/scripts/test-alive.sh
  infra/terraform/backend.tf
  infra/terraform/instance.tf
  infra/terraform/output.tf
  infra/terraform/provider.tf
  infra/terraform/template.tf
  infra/terraform/variable.tf
  infra/terraform/version.tf
Labels: feature

#57 Enhancement/tf smart variables
  .github/workflows/deploy.yml
  .github/workflows/pr.yml
  Makefile
  backend/src/main.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  infra/scripts/deploy.sh
  infra/terraform/env.json
  infra/terraform/instance.tf
  infra/terraform/template.tf
  infra/terraform/variable.tf
Labels: enhancement

#56 Feature/informative pages
  frontend/src/components/HeaderMain.vue
  frontend/src/components/UploadComponent.vue
  frontend/src/router/index.js
  frontend/src/views/About.vue
  frontend/src/views/Contact.vue
  frontend/src/views/Informations.vue
  frontend/src/views/Legal.vue
  frontend/src/views/text_content/AboutTextContent.vue
  frontend/src/views/text_content/ContactTextContent.vue
  frontend/src/views/text_content/LegalTextContent.vue
Labels: feature

#55 Enhancement/upload images ovh
  .github/workflows/pr.yml
  Makefile
  backend/Dockerfile
  backend/README.md
  backend/requirements.txt
  backend/src/main.py
  backend/src/model.py
  backend/tests/test_api.py
  backend/tests/test_model.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  frontend/src/components/ResultsComponent.vue
  frontend/src/components/UploadButton.vue
  frontend/src/store.js
Labels: enhancement

#58 Feature/cd prod
  .github/workflows/release.yml
  infra/scripts/deploy.sh
Labels: feature

#60 Enhancement/model eff b4 2022 03 02 08
  Makefile
  backend/Dockerfile
  backend/README.md
  backend/src/main.py
  backend/src/model.py
  backend/tests/test_api.py
  backend/tests/test_model.py
  frontend/package-lock.json
  frontend/package.json
Labels: enhancement

#59 Feature/logging feedback
  backend/src/main.py
  backend/tests/test_api.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ResultsComponent.vue
Labels: feature

#63 Change few stuff for better UI about prediction results
  backend/src/main.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/ResultsComponent.vue
Labels: bug

#64 removed pagination bullets
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/OnboardingSwiper.vue
Labels: bug

#65 Show Analyzing message right after having uploaded instead of after resize
  frontend/src/components/UploadButton.vue
Labels: bug
