Repository dnum-mi/basegun, pull requests merged in 2023-03, with the labels that each got.

#132 fix empty localStorage on result page
  frontend/src/main.css
  frontend/src/router/index.js
  frontend/src/utils/storage-utils.js
  frontend/src/views/GuideFactice/GuideFactice.vue
  frontend/src/views/Result.vue
  frontend/src/views/SafetyRecommendation.vue
Labels: bug, feature

#143 refactor: :art: Refactoring Result component
  frontend/src/views/Result.vue
Labels: enhancement, feature

#148 feat: 📊 Logging the detection of dummy or real firearms
  backend/src/main.py
  backend/tests/test_api.py
  docker-compose-dev.yml
  frontend/src/router/index.js
  frontend/src/views/GuideFactice/AskingExpert.vue
  frontend/src/views/GuideFactice/GuideFactice.vue
  frontend/src/views/GuideFactice/StopTutorial.vue
  frontend/src/views/Result.vue
  infra/scripts/test-alive.sh
Labels: feature

#144 refactor: :art: Refactoring HeaderMain with DsfrHeader component
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/components/HeaderMain.vue
  frontend/src/components/OnboardingSwiper.vue
  frontend/src/icons.js
  frontend/src/router/index.js
  frontend/src/views/About.vue
  frontend/src/views/Contact.vue
  frontend/src/views/InformationTabs/AboutInformationTabs.vue
  frontend/src/views/InformationTabs/ContactInformationTabs.vue
  frontend/src/views/InformationTabs/LegalInformationTabs.vue
  frontend/src/views/Informations.vue
  frontend/src/views/Legal.vue
  frontend/src/views/SafetyRecommendation.vue
Labels: enhancement

#149 enh: ♻️ migrate components vue2 to vue3
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/OnboardingSwiper.vue
  frontend/src/components/UploadButton.vue
  frontend/src/views/Home.vue
Labels: enhancement

#151 enh: ♻️ remove bootstrap and replace by Dsfr classes
  frontend/package-lock.json
  frontend/package.json
  frontend/src/.stylelintrc.js
  frontend/src/components/OnboardingSwiper.vue
  frontend/src/components/SnackbarAlert.vue
  frontend/src/main.css
  frontend/src/main.js
  frontend/src/views/GuideFactice/AskingExpert.vue
  frontend/src/views/GuideFactice/ExtractMag.vue
  frontend/src/views/GuideFactice/FirearmDirection.vue
  frontend/src/views/GuideFactice/GuideFactice.vue
  frontend/src/views/GuideFactice/SelectAmmo.vue
  frontend/src/views/GuideFactice/SelectOption.vue
  frontend/src/views/GuideFactice/StopTutorial.vue
  frontend/src/views/Home.vue
  frontend/src/views/Instructions.vue
  frontend/src/views/Result.vue
  frontend/src/views/SafetyRecommendation.vue
  frontend/vite.config.js
Labels: enhancement
