Repository dnum-mi/basegun, pull requests merged in 2023-09, with the labels that each got.

#181 Use a log file instead of STDOUT for logging
  README.md
  backend/Dockerfile
  backend/README.md
  backend/src/main.py
  backend/tests/test_api.py
  docker-compose-dev.yml
  docker-compose-prod.yml
  frontend/nginx.conf
  frontend/vite.config.js
  infra/kube/helm/templates/configmap.yaml
  infra/kube/helm/values.yaml
Labels: bug

#180 feat: :sparkles: add a different security message for civilians
  frontend/cypress.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.vue
  frontend/src/assets/guide-mise-en-securite/icones/take-care.jpg
  frontend/src/assets/guide-mise-en-securite/photos/autre_pistolet/autre_pistolet_derringer.jpg
  frontend/src/assets/guide-mise-en-securite/photos/autre_pistolet/autre_pistolet_drulov.jpg
  frontend/src/assets/guide-mise-en-securite/photos/autre_pistolet/autre_pistolet_fusil_scie.jpg
  frontend/src/assets/guide-mise-en-securite/photos/autre_pistolet/autre_pistolet_thompson.jpg
  frontend/src/assets/guide-mise-en-securite/photos/epaule_a_levier_sous_garde/epaule_levier_ss_garde_magasin_avant.jpg
  frontend/src/assets/guide-mise-en-securite/photos/epaule_a_levier_sous_garde/epaule_levier_ss_garde_magasin_fixe.jpg
  frontend/src/assets/guide-mise-en-securite/photos/pistolet_semi_auto_moderne/pistolet_pontet.jpg
  frontend/src/assets/guide-mise-en-securite/photos/pistolet_semi_auto_moderne/pistolet_semi_auto_pontet.jpg
  frontend/src/assets/guide-mise-en-securite/photos/pistolet_semi_auto_moderne/pistolet_semi_auto_talon.jpg
  frontend/src/assets/guide-mise-en-securite/photos/pistolet_semi_auto_moderne/pistolet_talon.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_1_cheminees.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_1873_US.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_axe_barillet.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_bouton_barillet.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_bouton_cote_barillet.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_cartouches.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_ew_brisure.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_portiere.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_2_sw_brisure.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_3_1873_FR.jpg
  frontend/src/assets/guide-mise-en-securite/photos/revolver/revolver_3_1892.jpg
  frontend/src/assets/guide-mise-en-securite/photos/semi_auto_militaire_autre/semi_auto_mil_ak.jpg
  frontend/src/assets/guide-mise-en-securite/photos/semi_auto_militaire_autre/semi_auto_mil_ar15.jpg
  frontend/src/assets/guide-mise-en-securite/photos/semi_auto_militaire_autre/semi_auto_mil_sten.jpg
  frontend/src/assets/guide-mise-en-securite/photos/semi_auto_militaire_autre/semi_auto_mil_thompson.jpg
  frontend/src/assets/guide-mise-en-securite/photos/semi_auto_militaire_autre/semi_auto_mil_uzi.jpg
  frontend/src/assets/guide-mise-en-securite/videos/epaule_a_pompe/epaule_pompe_simple.mp4
  frontend/src/assets/guide-mise-en-securite/videos/revolver/revolver_bouton_barillet.mp4
  frontend/src/main.js
  frontend/src/utils/firearms-utils/pistolet-semi-auto-moderne.js
  frontend/src/utils/firearms-utils/revolver.js
  frontend/src/utils/firearms-utils/semi-auto-style-militaire-autre.js
  frontend/src/views/GuideIdentificationFirearm/IdentificationSelectAmmo.vue
  frontend/src/views/GuideSecuringFirearm/SecuringRecommendations.vue
  frontend/src/views/GuideSecuringFirearm/SecuringSelectOptionStep1.vue
  frontend/src/views/GuideSecuringFirearm/SecuringSelectOptionStep2.vue
  frontend/src/views/GuideSecuringFirearm/SecuringSelectOptionStep3.vue
  frontend/src/views/GuideSecuringFirearm/SecuringTutorialContent.vue
Labels: feature

#184 Single requirements file
  backend/Dockerfile
  backend/requirements.txt
  backend/requirements/dev.txt
  backend/requirements/prod.txt
Labels: enhancement
